/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;

import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;

import modelo.beans.User;
import modelo.beans.Venta;
import modelo.dao.VentaDao;
import modelo.principal.Principal;

/**
 *
 * @author Usuario
 */
public class FrmVentasRealizadas extends javax.swing.JFrame {

    private final Integer id;

    /**
     * Creates new form VentasRealizadas
     */
    public FrmVentasRealizadas(User users) {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextField1.setText(users.getCorreo());
        this.id = users.getId();

        listarVentas();

    }

    public void listarVentas() {
        DefaultTableModel defaultTableModel = new DefaultTableModel(new String[]{"No.", "Codigo paquetes", "Origen", "Destino", "NIT", "Tipo de pago", "Tamanio del paquete", "N. paquetes", "Total"}, VentaDao.ventas.size());
        jTable1.setModel(defaultTableModel);

        TableModel modeloDatos = jTable1.getModel();

        for (Integer i = 0; i < VentaDao.getSalesById(id).size(); i++) {
            Venta venta = VentaDao.getSalesById(id).get(i);
            modeloDatos.setValueAt(venta.getnFactura(), i, 0);
            modeloDatos.setValueAt(venta.getnCodigoPq(), i, 1);
            modeloDatos.setValueAt(venta.getDireccionOrig(), i, 2);
            modeloDatos.setValueAt(venta.getDireccionDest(), i, 3);
            modeloDatos.setValueAt(venta.getNit(), i, 4);
            modeloDatos.setValueAt(venta.getTipoDePago(), i, 5);
            modeloDatos.setValueAt(venta.getTipoDePesoPaquete(), i, 6);
            modeloDatos.setValueAt(venta.getnPaquete(), i, 7);
            modeloDatos.setValueAt(venta.getTotal(), i, 8);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Bienvenido(a)");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Codigo Paquete", "Origen", "Destino", "NIT", "Tipo de pago", "Tamanio del paquete", "N. paquete", "total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Descargar Factuira");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Descargar Guia");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(116, 116, 116)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        FrmUsuario1 frmUsuario1 = new FrmUsuario1(Principal.obtener(jTextField1.getText()));
        frmUsuario1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);

        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }

        Document document = new Document();

        try {
            PdfWriter.getInstance(document, new FileOutputStream(path + "factura.pdf"));

            document.open();
            PdfPTable tabla = new PdfPTable(9);
            Paragraph paragraphHello = new Paragraph();
            paragraphHello.add("Orden de factura");
            document.add(paragraphHello);

            tabla.addCell("No. Fact");
            tabla.addCell("Codigo Paquete");
            tabla.addCell("Origen");
            tabla.addCell("Destino");
            tabla.addCell("NIT");
            tabla.addCell("tipo de pago");
            tabla.addCell("Tamanio");
            tabla.addCell("N paquete");
            tabla.addCell("Total");

            for (int i = 0; i < jTable1.getRowCount(); i++) {

                String fact = jTable1.getValueAt(i, 0).toString();
                String CodigoP = jTable1.getValueAt(i, 1).toString();
                String Origen = jTable1.getValueAt(i, 2).toString();
                String Destino = jTable1.getValueAt(i, 3).toString();
                String NIT = jTable1.getValueAt(i, 4).toString();
                String tipoPago = jTable1.getValueAt(i, 5).toString();
                String Tamanio = jTable1.getValueAt(i, 6).toString();
                String paquete = jTable1.getValueAt(i, 7).toString();
                String Total = jTable1.getValueAt(i, 8).toString();

                tabla.addCell(fact);
                tabla.addCell(CodigoP);
                tabla.addCell(Origen);
                tabla.addCell(Destino);
                tabla.addCell(NIT);
                tabla.addCell(tipoPago);
                tabla.addCell(Tamanio);
                tabla.addCell(paquete);
                tabla.addCell(Total);

            }
            document.add(tabla);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmVentasRealizadas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(FrmVentasRealizadas.class.getName()).log(Level.SEVERE, null, ex);
        }
        document.close();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);

        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }

        Document document = new Document();

        try {
            PdfWriter.getInstance(document, new FileOutputStream(path + "guia.pdf"));

            document.open();
            PdfPTable tabla = new PdfPTable(7);
            Paragraph paragraphHello = new Paragraph();
            paragraphHello.add("Guia de paquete");
            document.add(paragraphHello);

            tabla.addCell("Codigo Paquete");
            tabla.addCell("Origen");
            tabla.addCell("Destino");
            tabla.addCell("tipo de pago");
            tabla.addCell("Tamanio");
            tabla.addCell("N paquete");
            tabla.addCell("Total");

            for (int i = 0; i < jTable1.getRowCount(); i++) {

                String CodigoP = jTable1.getValueAt(i, 1).toString();
                String Origen = jTable1.getValueAt(i, 2).toString();
                String Destino = jTable1.getValueAt(i, 3).toString();
                String tipoPago = jTable1.getValueAt(i, 5).toString();
                String Tamanio = jTable1.getValueAt(i, 6).toString();
                String paquete = jTable1.getValueAt(i, 7).toString();
                String Total = jTable1.getValueAt(i, 8).toString();

                tabla.addCell(CodigoP);
                tabla.addCell(Origen);
                tabla.addCell(Destino);
                tabla.addCell(tipoPago);
                tabla.addCell(Tamanio);
                tabla.addCell(paquete);
                tabla.addCell(Total);

            }

            Paragraph paragraph = new Paragraph();
            paragraph.add("Fecha: 15/03/2023");
            document.add(paragraph);
            document.add(tabla);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmVentasRealizadas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(FrmVentasRealizadas.class.getName()).log(Level.SEVERE, null, ex);
        }
        document.close();

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentasRealizadas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentasRealizadas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentasRealizadas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentasRealizadas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentasRealizadas(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
